/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package misFormularios;

/**
 *
 * @author Cristopher
 */
public class Carteleras extends javax.swing.JInternalFrame{

    /**
     * Creates new form Carteleras
     */
    public Carteleras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel65 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(153, 255, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 255, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel23.setText("12:00 PM");

        jLabel24.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel24.setText("8:00 PM");

        jLabel25.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel25.setText("10:30 PM ");

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel10.setText("Funciones:");

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel11.setText("Funciones:");

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel12.setText("Funciones:");

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel13.setText("Funciones:");

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel14.setText("3:00 pm ");

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel15.setText("4:30 pm");

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel16.setText("6:00 pm");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nic/pelis/LaCiudad.png"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nic/pelis/Minions.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel17.setText("1:20 PM");

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel18.setText("4:15 PM");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nic/pelis/Spider.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nic/pelis/Thor.jpg"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel5.setText("LA CIUDAD PERDIDA");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel6.setText("MINIONS:ORIGEN DE GRU");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel7.setText("Thor Amor y Trueno");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel8.setText("Spider-man: Sin camino a casa");

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel19.setText("6:45 PM");

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel20.setText("2:00 PM");

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel21.setText("5:30 PM");

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel22.setText("7:15 PM");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 804, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );

        jLabel26.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel26.setText("12:00 PM");

        jLabel27.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel27.setText("8:00 PM");

        jLabel28.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel28.setText("10:30 PM ");

        jLabel29.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel29.setText("Funciones:");

        jLabel30.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel30.setText("Funciones:");

        jLabel31.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel31.setText("Funciones:");

        jLabel32.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel32.setText("Funciones:");

        jLabel33.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel33.setText("3:00 pm ");

        jLabel34.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel34.setText("4:30 pm");

        jLabel35.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel35.setText("6:00 pm");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nic/pelis/LaCiudad.png"))); // NOI18N

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nic/pelis/Minions.png"))); // NOI18N

        jLabel37.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel37.setText("1:20 PM");

        jLabel38.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel38.setText("4:15 PM");

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nic/pelis/Spider.jpg"))); // NOI18N

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nic/pelis/Thor.jpg"))); // NOI18N

        jLabel41.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel41.setText("LA CIUDAD PERDIDA");
        jLabel41.setToolTipText("");

        jLabel42.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel42.setText("MINIONS:ORIGEN DE GRU");

        jLabel43.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel43.setText("Thor Amor y Trueno");

        jLabel44.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel44.setText("Spider-man: Sin camino a casa");

        jLabel45.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel45.setText("6:45 PM");

        jLabel46.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel46.setText("2:00 PM");

        jLabel47.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel47.setText("5:30 PM");

        jLabel48.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel48.setText("7:15 PM");

        setBackground(new java.awt.Color(255, 255, 153));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(197, 175, 175));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel49.setText("12:00 PM");
        jPanel5.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 399, -1, -1));

        jLabel50.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel50.setText("8:00 PM");
        jPanel5.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 489, -1, -1));

        jLabel51.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel51.setText("10:30 PM ");
        jPanel5.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel52.setText("Funciones:");
        jPanel5.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, -1, -1));

        jLabel53.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel53.setText("Funciones:");
        jPanel5.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 360, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel54.setText("Funciones:");
        jPanel5.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 87, -1, -1));

        jLabel55.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel55.setText("Funciones:");
        jPanel5.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 90, -1, -1));

        jLabel56.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel56.setText("3:00 pm ");
        jPanel5.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 490, -1, -1));

        jLabel57.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel57.setText("4:30 pm");
        jPanel5.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, -1, -1));

        jLabel58.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel58.setText("6:00 pm");
        jPanel5.add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 126, -1, -1));

        jLabel59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nic/pelis/LaCiudad.png"))); // NOI18N
        jPanel5.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 43, -1, -1));

        jLabel60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nic/pelis/Minions.png"))); // NOI18N
        jPanel5.add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 43, -1, -1));

        jLabel61.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel61.setText("1:20 PM");
        jPanel5.add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, -1, -1));

        jLabel62.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel62.setText("4:15 PM");
        jPanel5.add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 390, -1, -1));

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nic/pelis/Spider.jpg"))); // NOI18N
        jPanel5.add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 323, 181, -1));

        jLabel64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nic/pelis/Thor.jpg"))); // NOI18N
        jPanel5.add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 323, 178, -1));

        jLabel65.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel65.setText("LA CIUDAD PERDIDA");
        jLabel65.setToolTipText("");
        jPanel5.add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 60, -1, -1));

        jLabel66.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel66.setText("MINIONS:ORIGEN DE GRU");
        jPanel5.add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        jLabel67.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel67.setText("THOR AMOR Y TRUENO");
        jPanel5.add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        jLabel68.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel68.setText("SPIDER-MAN:SIN CAMINO A CASA");
        jPanel5.add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 323, -1, -1));

        jLabel69.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel69.setText("6:45 PM");
        jPanel5.add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        jLabel70.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel70.setText("2:00 PM");
        jPanel5.add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        jLabel71.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel71.setText("5:30 PM");
        jPanel5.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 444, -1, -1));

        jLabel72.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel72.setText("7:15 PM");
        jPanel5.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, -1, -1));

        jLabel73.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel73.setText("CARTELERA");
        jPanel5.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 11, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 925, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carteleras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carteleras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carteleras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carteleras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Carteleras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
