/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package misFormularios;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class frmReseñas extends javax.swing.JFrame {

    /**
     * Creates new form frmReseñas
     */
    public frmReseñas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxPeliculas = new javax.swing.JComboBox<>();
        lblDescripcion = new javax.swing.JLabel();
        btnSleccionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbxPeliculas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxPeliculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MINIONS - EL ORIGEN DE GRU", "THOR AMOR Y TRUENO", "CIUDAD PERDIDA", "SPIDERMAN - SIN CAMINO A CASA" }));
        cbxPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPeliculasActionPerformed(evt);
            }
        });

        lblDescripcion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        btnSleccionar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnSleccionar.setText("Seleccionar");
        btnSleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSleccionarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Escoger una pelicula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                            .addComponent(cbxPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(btnSleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(cbxPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(lblDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnSleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPeliculasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPeliculasActionPerformed

    private void btnSleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSleccionarActionPerformed
        // TODO add your handling code here:
         String mensaje,descripcion1,descripcion2,descripcion3,descripcion;
                int p_posicion=0;
                p_posicion=cbxPeliculas.getSelectedIndex();
                if (p_posicion==0) 
                    lblDescripcion.setText("En los años 70, Gru crece siendo un gran admirador de \"Los salvajes seis\", un supergrupo de villanos."+
                            "Para demostrarles que puede ser malvado, Gru idea un plan con la esperanza de formar parte"+
                            "de la banda. Por suerte, cuenta con la ayuda de sus fieles seguidores, los Minions,"+
                            "siempre dispuestos a sembrar el caos.");
                else if(p_posicion==1)
                    lblDescripcion.setText("Thor está buscando la paz interior, pero la irrupción de Gorr, el asesino de dioses,"+
                            " le obliga a volver al combate. Thor recluta a la Reina Valkiria, Korg y su exnovia, "
                            + "Jane Foster, para que lo ayuden a evitar la extinción de los dioses.");
                            else if(p_posicion==2)
                                    lblDescripcion.setText("La escritora solitaria Loretta Sage escribe sobre lugares exóticos "
                                            + "en sus populares novelas de aventuras con un atractivo modelo de portada, Alan."
                                            + " Mientras está de gira promocionando su nuevo libro, es secuestrada por un excéntrico"
                                            + " multimillonario.");
                                    else if (p_posicion==3)
                                            lblDescripcion.setText("Tras descubrirse la identidad secreta de Peter Parker como Spider-Man,"
                                                    + " la vida del joven se vuelve una locura. Peter decide pedirle ayuda al Doctor Extraño"
                                                    + " para recuperar su vida. Pero algo sale mal y provoca una fractura en el multiverso.");
            
    }//GEN-LAST:event_btnSleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReseñas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSleccionar;
    private javax.swing.JComboBox<String> cbxPeliculas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDescripcion;
    // End of variables declaration//GEN-END:variables
}
