/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package misFormularios;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class frmReseñas extends javax.swing.JInternalFrame{

    /**
     * Creates new form frmReseñas
     */
    public frmReseñas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxPeliculas = new javax.swing.JComboBox<>();
        btnSleccionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblDescripcion = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(197, 175, 175));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(32767, 32767));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxPeliculas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbxPeliculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MINIONS - EL ORIGEN DE GRU", "THOR AMOR Y TRUENO", "CIUDAD PERDIDA", "SPIDERMAN - SIN CAMINO A CASA" }));
        cbxPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxPeliculasActionPerformed(evt);
            }
        });
        getContentPane().add(cbxPeliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 335, 30));

        btnSleccionar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btnSleccionar.setText("Seleccionar");
        btnSleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSleccionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 146, 43));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("ELIGE LA PELICULA");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 250, -1));

        lblDescripcion.setBackground(new java.awt.Color(197, 175, 175));
        lblDescripcion.setColumns(20);
        lblDescripcion.setRows(5);
        jScrollPane1.setViewportView(lblDescripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 598, 199));

        jPanel1.setBackground(new java.awt.Color(197, 175, 175));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cinta.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(660, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(83, 83, 83))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxPeliculasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxPeliculasActionPerformed

    private void btnSleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSleccionarActionPerformed
        // TODO add your handling code here:
         String mensaje,descripcion1,descripcion2,descripcion3,descripcion;
                int p_posicion=0;
                p_posicion=cbxPeliculas.getSelectedIndex();
                if (p_posicion==0) 
                    lblDescripcion.setText("En los años 70, Gru crece siendo un gran admirador de \"Los salvajes seis\", un supergrupo de villanos\n"+
                            "Para demostrarles que puede ser malvado, Gru idea un plan con la esperanza de formar parte\n"+
                            "de la banda. Por suerte, cuenta con la ayuda de sus fieles seguidores, los Minions,\n"+
                            "siempre dispuestos a sembrar el caos.\n");
                else if(p_posicion==1)
                    lblDescripcion.setText("Thor está buscando la paz interior, pero la irrupción de Gorr, el asesino de dioses,\n"+
                            " le obliga a volver al combate. Thor recluta a la Reina Valkiria, Korg y su exnovia, \n"
                            + "Jane Foster, para que lo ayuden a evitar la extinción de los dioses.\n");
                            else if(p_posicion==2)
                                    lblDescripcion.setText("La escritora solitaria Loretta Sage escribe sobre lugares exóticos \n"
                                            + "en sus populares novelas de aventuras con un atractivo modelo de portada, Alan.\n"
                                            + " Mientras está de gira promocionando su nuevo libro, es secuestrada por un excéntrico\n"
                                            + " multimillonario.\n");
                                    else if (p_posicion==3)
                                            lblDescripcion.setText("Tras descubrirse la identidad secreta de Peter Parker como Spider-Man, la vida\n"
                                                    + " del joven se vuelve una locura. Peter decide pedirle ayuda al Doctor Strange\n"
                                                    + " para recuperar su vida. Pero algo sale mal y provoca una fractura en el multiverso.\n");
            
    }//GEN-LAST:event_btnSleccionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmReseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmReseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmReseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmReseñas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmReseñas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSleccionar;
    private javax.swing.JComboBox<String> cbxPeliculas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblDescripcion;
    // End of variables declaration//GEN-END:variables
}
