package misFormularios;
import FormulariosCompra.*;
import misFormularios.*;
import misFormularios.frmReseñas;
public class menuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public menuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Escritorio = new javax.swing.JDesktopPane();
        Cartelera = new javax.swing.JLabel();
        Reseñas = new javax.swing.JLabel();
        Boleteria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CineLogo.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 220));

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 647, Short.MAX_VALUE)
        );

        jPanel1.add(Escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 0, 940, 647));

        Cartelera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo-cartelera.png"))); // NOI18N
        Cartelera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CarteleraMouseClicked(evt);
            }
        });
        jPanel1.add(Cartelera, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, 120));

        Reseñas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo-reseña.png"))); // NOI18N
        Reseñas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReseñasMouseClicked(evt);
            }
        });
        jPanel1.add(Reseñas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        Boleteria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logo-boleteria.png"))); // NOI18N
        Boleteria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoleteriaMouseClicked(evt);
            }
        });
        jPanel1.add(Boleteria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 210, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoleteriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoleteriaMouseClicked
     Boleteria verVentana=new Boleteria();
     Escritorio.add(verVentana);
     verVentana.show();
    }//GEN-LAST:event_BoleteriaMouseClicked

    private void ReseñasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReseñasMouseClicked
    frmReseñas verVentana=new frmReseñas();
    Escritorio.add(verVentana);
    verVentana.show();
    }//GEN-LAST:event_ReseñasMouseClicked

    private void CarteleraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CarteleraMouseClicked
     Carteleras verVentana=new Carteleras();
     Escritorio.add(verVentana);
     verVentana.show();
    }//GEN-LAST:event_CarteleraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Boleteria;
    private javax.swing.JLabel Cartelera;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JLabel Reseñas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
